version: '3.8'
 
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 956282
      MYSQL_DATABASE: WebProject
    # ports: (This is optional and mainly used for external access to the database)
    #   - "3306:3306"
 
  web:
    image: haoxuanyu/final:latest
    ports:
      - "8081:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: production
    depends_on:
      - db
