version: '3.8'

networks:
  final:
    driver: bridge

services:
  frontend:
    container_name: final-frontend
    image: haoxuanyu/final-frontend:latest
    networks:
      - final
    ports:
      - "80:3000"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
  db:
    container_name: final-db
    image: mysql:latest
    ports:
      - "3306:3306"
    networks:
      - final
    environment:
      - "MYSQL_DATABASE=${DB_NAME}"
      - "MYSQL_ROOT_PASSWORD=${DB_PASSWORD}"
    volumes:
      - ./mysql:/var/lib/mysql