version: '3.3'
 
services:
  app:
    build: .
    ports:
      - "8080:3000"
    environment:
      DATABASE_HOST: mysql
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: mydatabase
    depends_on:
      - mysql
    restart: always
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
 
volumes:
  mysql_data:
 
volumes:
  db-data:
