version: '3.8'
 
services:
  db:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 956282
      MYSQL_DATABASE: webproject
    ports:
      - "3306:3306"
 
  web:
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: 956282
      DB_NAME: webproject
    depends_on:
      - db
 
volumes:
  db-data:
